### ISSUE TITLE
Confusing structure

### ISSUE THREAD

**Issue by bloodmandarin** [Mindful-Meerkats/mindful-meerkats-org#1]
For someone who is not a programmer, like me, I have difficulty understanding where I can change certain text blocks. I will now just create issues for the things I noticed, but of course it would be easier if I could make the changes on my own.

**Comment by orschiro** [comment]
Thanks for the feedback. 

I have created a separate issue to remember for myself: https://github.com/Mindful-Meerkats/mindful-meerkats-org/issues/7

For now, if you want to make changes to the website, create yourself an account on our Wordpress blog: https://www.mindful-meerkats.org/wp-login.php

**Comment by bloodmandarin** [comment]
I have an account on Wordpress. Can you add bloodmandarin as a editor to the wordpress or shall I access it with Keepass?

**Comment by orschiro** [comment]
You should be able to register yourself with your Wordpress.com account:

![image](https://cloud.githubusercontent.com/assets/170947/10711503/a1f53fea-7a7d-11e5-83c7-14be7853f606.png)

**Comment by bloodmandarin** [comment]
Perfect.
