### ISSUE TITLE
Grammar mistake on Meeka-page

### ISSUE THREAD

**Issue by bloodmandarin** [Mindful-Meerkats/mindful-meerkats-org#2]
Change "We are currently working on an exciting game that will make you live happier." into "We are currently working on an exciting game that will empower you to live a happier life by showing you the daily choices that you have."

**Comment by orschiro** [comment]
![image](https://cloud.githubusercontent.com/assets/170947/10711368/1c14b1de-7a79-11e5-86ff-b3e70c53a39d.png)
