### ISSUE TITLE
Weird-sounding section

### ISSUE THREAD

**Issue by bloodmandarin** [Mindful-Meerkats/mindful-meerkats-org#3]
"Currently only allow" does not sound right.

**Comment by orschiro** [comment]
Can you always provide a screenshot for the future? 

That makes it easier for me to find the reference. 

Thanks!

Robert

![image](https://cloud.githubusercontent.com/assets/170947/10711354/c1b510b2-7a78-11e5-80d5-f0dca09cd980.png)
